apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-client
spec:
  selector:
    matchLabels:
      app: student-app-client
  replicas: {{ .Values.frontend.replicas }}
  template:
    metadata:
      labels:
        app: student-app-client
    spec:
      containers:
        - name: student-app-client
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 80
