name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          check-latest: false
      - name: Build with Maven
        run: mvn clean install
        working-directory: spring-boot-student-app-api
      - name: Run tests
        run: mvn test
        working-directory: spring-boot-student-app-api
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact-${{ github.sha }}
          path: spring-boot-student-app-api/target/*.jar

  build_frontend:
    runs-on: ubuntu-latest
    needs: build_backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
        working-directory: react-student-management-web-app
      - name: Build React app
        run: CI=false npm run build
        working-directory: react-student-management-web-app

  docker_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          check-latest: false
      - name: Build with Maven
        run: mvn clean install
        working-directory: spring-boot-student-app-api
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
        working-directory: spring-boot-student-app-api
      - name: Push backend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

  docker_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .
        working-directory: react-student-management-web-app
      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
